export const defaultState = {
  projects: [
    {
      name: "Refactor tests",
      id: "P1",
      language: "en",
      owner: "U1",
      isComplete: false,
    },
    {
      name: "Meet with CTO",
      id: "P2",
      language: "en",
      owner: "U1",
      isComplete: true,
    },
    {
      name: "Compile ES6",
      id: "P3",
      language: "en",
      owner: "U2",
      isComplete: false,
    },
    {
      name: "Update component snapshots",
      id: "P4",
      language: "fr",
      owner: "U1",
      isComplete: true,
    },
    {
      name: "Production optimizations",
      id: "P5",
      language: "fr",
      owner: "U1",
      isComplete: false,
    },
    {
      name: "Production optimizations",
      id: "P6",
      language: "fr",
      owner: "U1",
      isComplete: false,
    },
    {
      name: "Update component snapshots",
      id: "P7",
      language: "fr",
      owner: "U1",
      isComplete: true,
    },
    {
      name: "Production optimizations",
      id: "P8",
      language: "fr",
      owner: "U1",
      isComplete: false,
    },
    {
      name: "Production optimizations",
      id: "P9",
      language: "fr",
      owner: "U1",
      isComplete: false,
    },
  ],
  languages: [
    {
      id: "en",
      htmlTitle: "Modokemdev | en",
      name: "English",
      title: "Welcome to Modokemdev",
      description: "C# developer at day, Dragon Rider at night.",
    },
    {
      id: "fr",
      htmlTitle: "Modokemdev | fr",
      name: "Français",
      title: "Bienvenue à Modokemdev",
      description: "Développeur C# le jour, Dragon Rider la nuit.",
    },
    {
      id: "es",
      htmlTitle: "Modokemdev | es",
      name: "Español",
      title: "Bienvenido a Modokemdev",
      description: "Desarollador C# de día, Dragon Rider de noche.",
    },
  ],
  pageNotFound: [
    {
      id: 404,
      htmlTitle: "404 - Page not found",
      name: "Page not found",
      title: "404 - Page not found",
      description: "You are lost!",
    },
  ],
};
